site_name: w.paper的小站
site_description: w.paper 的个人小站

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
  palette:
    scheme: default

extra_css:
  - assets/css/morandi.css

extra_javascript:
  - assets/js/zju.js

nav:
  - 主页: index.md
  - 课程: course/index.md
  - 运动: sports/index.md
  - 娱乐: fun/index.md
  - 音乐: music/index.md
  - 阅读: 
    - 《置身事内》书摘: reading/zhishenshinei.md
  - 友链: friends/index.md
  - 关于: about/index.md
